default: &default
  adapter: postgis
  encoding: unicode
  username: <%= ENV.fetch('RDS_USERNAME') { 'postgres' } %>
  password:
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch('RDS_HOSTNAME') { 'localhost' } %>

development:
  <<: *default
  database: db/tolenno_development

test:
  <<: *default
  database: db/tolenno_test

production:
  <<: *default
  database: <%= ENV['RDS_DB_NAME'] %>
  password: <%= ENV['RDS_PASSWORD'] %>
  port: <%= ENV['RDS_PORT'] %>
